// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvuB_LVNgXF6GxoPvgb3jCvfPOl8bm8Wo',
    appId: '1:314486986818:web:0c03ba805b6876651475db',
    messagingSenderId: '314486986818',
    projectId: 'contacts-ebdfe',
    authDomain: 'contacts-ebdfe.firebaseapp.com',
    storageBucket: 'contacts-ebdfe.appspot.com',
    measurementId: 'G-XFNC2KQFWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPaVpckQc4g_graYaNmb6S07PHqLrxe0',
    appId: '1:314486986818:android:3bf33a9dbedbed4d1475db',
    messagingSenderId: '314486986818',
    projectId: 'contacts-ebdfe',
    storageBucket: 'contacts-ebdfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0mosvsymqNpjzXwsakUXVTpXaDHeb4jA',
    appId: '1:314486986818:ios:ddb4a6e6bd2dfe141475db',
    messagingSenderId: '314486986818',
    projectId: 'contacts-ebdfe',
    storageBucket: 'contacts-ebdfe.appspot.com',
    iosClientId: '314486986818-ihr6pshlrrqvsip1mkd7phd1ae0t54st.apps.googleusercontent.com',
    iosBundleId: 'br.com.mbi.contacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0mosvsymqNpjzXwsakUXVTpXaDHeb4jA',
    appId: '1:314486986818:ios:ddb4a6e6bd2dfe141475db',
    messagingSenderId: '314486986818',
    projectId: 'contacts-ebdfe',
    storageBucket: 'contacts-ebdfe.appspot.com',
    iosClientId: '314486986818-ihr6pshlrrqvsip1mkd7phd1ae0t54st.apps.googleusercontent.com',
    iosBundleId: 'br.com.mbi.contacts',
  );
}
